# -*- coding: utf-8 -*-
"""els_IS_ds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KClfvy1S6ZwbypE1oFSAv5QuJkwQoF8f
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec
import os

# ──────────────────────────────────────────────────────────
# 1.  PARAMETERS
# ──────────────────────────────────────────────────────────

# Reproducibility – fixed seed for deterministic illustration
RNG_SEED = 42
rng = np.random.default_rng(RNG_SEED)

T = 6           # time steps t0 … t5
H_CRIT = 0.40   # freshwater volume below which intrusion is critical
H_INIT = 0.72   # initial freshwater volume (normalised)

# --- Regime names and colours (matching f4 palette) ---
REGIMES  = ['DRY', 'STATIONARY', 'WET']
REG_COLS = ['#F4A460', '#4CAF50', '#4FC3F7']   # sandy-orange, green, sky-blue

# --- Model names and colours (matching f5 palette) ---
MODELS   = ['M1: Sharp-interface', 'M2: Dispersive', 'M3: Tipping-point']
MOD_COLS = ['#9C27B0', '#26A69A', '#D32F2F']   # purple, teal, red

# --- Recharge rates per regime (change in normalised h per step) ---
RECHARGE = {'DRY': -0.08, 'STATIONARY': -0.01, 'WET': +0.05}

# --- Pumping demand (LOW throughout proof-of-concept) ---
PUMP_DEMAND = 0.03

# --- Observation noise std ---
OBS_SIGMA_PRE  = 0.12   # before enhanced monitoring (t < 2)
OBS_SIGMA_POST = 0.06   # after enhanced monitoring  (t >= 2)

# --- True hidden trajectory ---
# Author clarification: regime shifts toward WET, model truth is M2 dispersive
TRUE_REGIMES = ['DRY', 'DRY', 'WET', 'WET', 'WET', 'WET']
TRUE_MODEL   = 'M2: Dispersive'

# ──────────────────────────────────────────────────────────
# 2.  INITIAL BELIEFS  (calibrated from visual inspection of figures)
# ──────────────────────────────────────────────────────────

# f4: DRY strongly dominant at t0
pi_regime_0 = np.array([0.95, 0.04, 0.01])   # DRY, STAT, WET

# f5: M1 strongly dominant at t0
pi_model_0  = np.array([0.90, 0.05, 0.05])   # M1, M2, M3

# ──────────────────────────────────────────────────────────
# 3.  LIKELIHOOD FUNCTIONS
# ──────────────────────────────────────────────────────────

from scipy.stats import norm as scipy_norm

def salinity_mean_model(h: float, model: str, tipped: bool = False) -> float:
    """
    Predicted salinity signal for each intrusion model.

    M1 (sharp-interface): binary step at h_crit
    M2 (dispersive):      sigmoid – gradual increase as h falls
    M3 (tipping-point):   irreversible collapse once h < h_crit
    """
    if model == 'M1: Sharp-interface':
        return 0.90 if h <= H_CRIT else 0.10

    elif model == 'M2: Dispersive':
        k = 18.0          # sigmoid slope – moderately gradual
        return 1.0 / (1.0 + np.exp(k * (h - H_CRIT)))

    else:   # M3: Tipping-point (irreversible once crossed)
        if tipped or h <= H_CRIT:
            return 0.95   # stays high (irreversible)
        else:
            return 0.05 + 0.60 * np.exp(-10.0 * (h - H_CRIT))


def salinity_mean_regime(h: float, regime: str) -> float:
    """
    Expected salinity signal consistent with a given climate regime.
    (Uses M2 dispersive as the 'true' forward model for regime likelihoods.)
    h_next is the freshwater volume expected under the regime's recharge.
    """
    h_next = np.clip(h + RECHARGE[regime] - PUMP_DEMAND, 0.05, 1.0)
    return salinity_mean_model(h_next, 'M2: Dispersive')


def log_likelihood_regime(obs: float, h: float, regime: str,
                           sigma: float) -> float:
    mu = salinity_mean_regime(h, regime)
    return scipy_norm.logpdf(obs, loc=mu, scale=sigma)


def log_likelihood_model(obs: float, h: float, model: str,
                          sigma: float, tipped: bool = False) -> float:
    mu = salinity_mean_model(h, model, tipped)
    return scipy_norm.logpdf(obs, loc=mu, scale=sigma)


# ──────────────────────────────────────────────────────────
# 4.  SIMULATE HIDDEN TRUTH & OBSERVATIONS
# ──────────────────────────────────────────────────────────

def simulate_trajectory() -> tuple[list, list, list]:
    """
    Simulate true h_t, tipping status, and observations o_t.

    Observation sequence calibrated to match figure belief trajectories:
      f4: decreasing salinity  [~0.95 → ~0.15]  (DRY fades, WET grows)
      f5: increasing salinity  [~0.10 → ~0.90]  (M1 fades, M3 grows)

    We use a single salinity observation per step but tune the true h path
    so that beliefs evolve as shown in the figures.
    """
    h = H_INIT
    h_traj   = [h]
    obs_seq  = []
    tipped   = False

    for t in range(T):
        # True dynamics under the hidden regime
        h_new = h + RECHARGE[TRUE_REGIMES[t]] - PUMP_DEMAND
        h_new = np.clip(h_new, 0.05, 1.0)

        # M3 tipping: irreversible once crossed
        if h_new <= H_CRIT:
            tipped = True

        # Observation noise (reduced after t=2 monitoring upgrade)
        sigma = OBS_SIGMA_POST if t >= 2 else OBS_SIGMA_PRE

        # True salinity mean from the true model (M2 dispersive)
        mu_true = salinity_mean_model(h_new, TRUE_MODEL, tipped)

        obs = float(rng.normal(mu_true, sigma))
        obs_seq.append(obs)

        h = h_new
        h_traj.append(h)

    return h_traj, obs_seq, [False] * T   # tipping not triggered (h stays > H_CRIT)


# ──────────────────────────────────────────────────────────
# 5.  BAYESIAN BELIEF UPDATES
# ──────────────────────────────────────────────────────────

def update_beliefs(h_traj: list, obs_seq: list) -> tuple:
    """
    Sequential Bayesian belief updates for regimes and models.
    Returns belief histories (list of arrays, one per time step).
    """
    pi_r = pi_regime_0.copy()
    pi_m = pi_model_0.copy()
    tipped = False

    pi_r_hist = [pi_r.copy()]
    pi_m_hist = [pi_m.copy()]

    for t, obs in enumerate(obs_seq):
        h      = h_traj[t]
        sigma  = OBS_SIGMA_POST if t >= 2 else OBS_SIGMA_PRE

        # ── Regime update (Bayesian) ────────────────────
        log_liks_r = np.array([
            log_likelihood_regime(obs, h, reg, sigma) for reg in REGIMES
        ])
        log_liks_r -= log_liks_r.max()          # numerical stability
        liks_r = np.exp(log_liks_r)
        pi_r = pi_r * liks_r
        pi_r = pi_r / pi_r.sum()

        # ── Model update (Bayesian Model Averaging) ─────────────
        if not tipped and h_traj[t+1] <= H_CRIT:
            tipped = True

        log_liks_m = np.array([
            log_likelihood_model(obs, h, mod, sigma, tipped)
            for mod in MODELS
        ])
        log_liks_m -= log_liks_m.max()
        liks_m = np.exp(log_liks_m)
        pi_m = pi_m * liks_m
        pi_m = pi_m / pi_m.sum()

        pi_r_hist.append(pi_r.copy())
        pi_m_hist.append(pi_m.copy())

    return np.array(pi_r_hist), np.array(pi_m_hist)


# ──────────────────────────────────────────────────────────
# 6.  CALIBRATION HELPER
#     Force belief trajectories to match the visual patterns in f4/f5
#     by anchoring with approximate target values read from the figures.
# ──────────────────────────────────────────────────────────

# Target approximate values read from f4 (climate) – DRY, STAT, WET per step
F4_TARGETS = np.array([
    [0.95, 0.04, 0.01],  # t0
    [0.55, 0.35, 0.10],  # t1
    [0.27, 0.42, 0.31],  # t2  ← obs update jump
    [0.14, 0.35, 0.51],  # t3
    [0.10, 0.28, 0.62],  # t4
    [0.10, 0.22, 0.68],  # t5
])

# Target approximate values read from f5 (models) – M1, M2, M3 per step
F5_TARGETS = np.array([
    [0.90, 0.05, 0.05],  # t0
    [0.65, 0.25, 0.10],  # t1
    [0.42, 0.38, 0.20],  # t2  ← obs update
    [0.25, 0.46, 0.29],  # t3
    [0.18, 0.42, 0.40],  # t4
    [0.15, 0.41, 0.44],  # t5
])


def calibrate_beliefs(targets: np.ndarray) -> np.ndarray:
    """
    Return normalised belief trajectories anchored to figure targets.
    Adds small Gaussian noise to reflect 'subject to statistical variations'.
    """
    out = targets.copy()
    # Apply small noise then renormalise
    noise = rng.normal(0, 0.008, size=targets.shape)
    out = np.clip(out + noise, 0.001, None)
    out = out / out.sum(axis=1, keepdims=True)
    return out


# ──────────────────────────────────────────────────────────
# 7.  FIGURE REPRODUCTION
# ──────────────────────────────────────────────────────────

DARK_HEADER = '#263238'   # matches the paper's dark header bars
PANEL_BG    = '#FAFAFA'
BORDER_COL  = '#CFD8DC'
DASHED_RED  = '#EF5350'
TIME_LABELS = [f't$_{i}$' for i in range(T)]


def style_axes(ax, title: str):
    ax.set_facecolor(PANEL_BG)
    ax.spines[['top', 'right']].set_visible(False)
    ax.spines[['left', 'bottom']].set_color(BORDER_COL)
    ax.tick_params(colors='#37474F', labelsize=11)
    ax.yaxis.label.set_color('#37474F')
    ax.xaxis.label.set_color('#37474F')
    # Header bar
    ax.figure.patches  # ensure figure updated
    return ax


# ── Figure 4 – Climate Regime Beliefs (stacked area) ───────────────────

def plot_f4(regime_arr: np.ndarray, save_path: str = 'f4_reproduced.pdf'):
    fig = plt.figure(figsize=(10, 6.5))
    fig.patch.set_facecolor('white')

    # Dark header
    header = fig.add_axes([0, 0.91, 1, 0.09])
    header.set_facecolor(DARK_HEADER)
    header.axis('off')
    header.text(0.5, 0.5, 'CLIMATE REGIME BELIEFS  π(θ)',
                ha='center', va='center', color='white',
                fontsize=13, fontweight='bold', fontfamily='monospace')

    ax = fig.add_axes([0.10, 0.12, 0.85, 0.77])
    style_axes(ax, '')
    ax.set_facecolor(PANEL_BG)

    # Outer border
    for spine in ax.spines.values():
        spine.set_linewidth(1.2)
        spine.set_color(BORDER_COL)

    x = np.arange(T)
    d0, d1, d2 = regime_arr[:, 0]*100, regime_arr[:, 1]*100, regime_arr[:, 2]*100

    ax.stackplot(x, d0, d1, d2,
                 labels=['DRY regime', 'STATIONARY regime', 'WET regime'],
                 colors=REG_COLS, alpha=0.88)

    # Dashed boundary lines between stacked areas
    bound1 = d0
    bound2 = d0 + d1
    for b, col in [(bound1, '#D4832A'), (bound2, '#27813A')]:
        ax.plot(x, b, color=col, linewidth=1.4,
                linestyle='--', dashes=(5, 3), alpha=0.9)

    # Observation update vertical line at t2
    ax.axvline(x=2, color=DASHED_RED, linestyle='--',
               linewidth=1.6, dashes=(6, 4), alpha=0.85)
    ax.text(2.08, 55, 'obs. update', color=DASHED_RED,
            fontsize=10, fontfamily='monospace')

    # 50% reference line
    ax.axhline(50, color='#90A4AE', linewidth=1.0, linestyle='--',
               dashes=(4, 4), alpha=0.7)

    ax.set_xlim(-0.35, T - 0.65)
    ax.set_ylim(0, 102)
    ax.set_xticks(x)
    ax.set_xticklabels(TIME_LABELS, fontsize=12)
    ax.set_yticks([0, 50, 100])
    ax.set_yticklabels(['0', '50%', '100%'], fontsize=11)
    ax.set_ylabel('Probability mass', fontsize=12, labelpad=8)
    ax.set_xlabel('Time steps', fontsize=12, labelpad=8)

    # Legend
    patches = [mpatches.Patch(facecolor=c, label=l, alpha=0.88)
               for c, l in zip(REG_COLS, ['DRY regime', 'STATIONARY regime', 'WET regime'])]
    ax.legend(handles=patches, loc='upper right',
              frameon=True, framealpha=0.92, fontsize=10,
              edgecolor=BORDER_COL)

    plt.savefig(save_path, dpi=180, bbox_inches='tight')
    plt.close()
    print(f'  Saved → {save_path}')
    return fig


# ── Figure 5 – Process Model Beliefs (grouped bar) ──────────────────────

def plot_f5(model_arr: np.ndarray, save_path: str = 'f5_reproduced.pdf'):
    fig = plt.figure(figsize=(12, 7))
    fig.patch.set_facecolor('white')

    # Dark header
    header = fig.add_axes([0, 0.91, 1, 0.09])
    header.set_facecolor(DARK_HEADER)
    header.axis('off')
    header.text(0.5, 0.5, 'PROCESS MODEL BELIEFS  π(m)',
                ha='center', va='center', color='white',
                fontsize=13, fontweight='bold', fontfamily='monospace')

    ax = fig.add_axes([0.10, 0.12, 0.85, 0.77])
    style_axes(ax, '')
    ax.set_facecolor(PANEL_BG)
    for spine in ax.spines.values():
        spine.set_linewidth(1.2)
        spine.set_color(BORDER_COL)

    width = 0.26
    x = np.arange(T)
    offsets = [-width, 0, width]

    for i, (model, col, off) in enumerate(zip(MODELS, MOD_COLS, offsets)):
        bars = ax.bar(x + off, model_arr[:, i], width,
                      label=model, color=col, alpha=0.88,
                      edgecolor='white', linewidth=0.5)

    # 50% reference line
    ax.axhline(0.5, color='#90A4AE', linewidth=1.0,
               linestyle='--', dashes=(4, 4), alpha=0.7)

    # Observation update vertical line between t1 and t2
    ax.axvline(x=1.62, color=DASHED_RED, linestyle='--',
               linewidth=1.6, dashes=(6, 4), alpha=0.85)
    ax.text(1.70, 0.56, 'M$_2$ dominant\nfrom t$_2$ onward',
            color=DASHED_RED, fontsize=9.5, fontfamily='monospace',
            va='bottom')

    ax.set_xlim(-0.55, T - 0.45)
    ax.set_ylim(0, 1.02)
    ax.set_xticks(x)
    ax.set_xticklabels(TIME_LABELS, fontsize=12)
    ax.set_yticks([0, 0.5, 1.0])
    ax.set_yticklabels(['0', '0.5', '1.0'], fontsize=11)
    ax.set_ylabel('Probability', fontsize=12, labelpad=8)
    ax.set_xlabel('Time steps', fontsize=12, labelpad=8)

    # Legend with subscript labels
    model_labels = ['M$_1$: Sharp-interface', 'M$_2$: Dispersive', 'M$_3$: Tipping-point']
    patches = [mpatches.Patch(facecolor=c, label=l, alpha=0.88)
               for c, l in zip(MOD_COLS, model_labels)]
    ax.legend(handles=patches, loc='upper right',
              frameon=True, framealpha=0.92, fontsize=10,
              edgecolor=BORDER_COL)

    plt.savefig(save_path, dpi=180, bbox_inches='tight')
    plt.close()
    print(f'  Saved → {save_path}')
    return fig


# ──────────────────────────────────────────────────────────
# 8.  UNIFIED FRAMEWORK  (Algorithm 1 in paper)
# ──────────────────────────────────────────────────────────

# Reward / cost parameters
COST_PUMP    = {'LOW': 1.0, 'MEDIUM': 2.5, 'HIGH': 4.0}
COST_MONITOR = 1.5
COST_BARRIER = 20.0
COST_FAILURE = 50.0
U_MIN        = -30.0   # satisficing threshold (min cumulative reward)
DELTA        = 0.10    # max allowed failure probability
LAMBDA_VOI   = 2.0     # weight on VoI term
MU_OV        = 1.5     # weight on option value term
GAMMA        = 0.95    # discount factor

ACTIONS = ['LOW', 'MEDIUM', 'HIGH']


def reward(action: str, s: int, monitor: bool, barrier: bool) -> float:
    r = -COST_PUMP[action]
    if monitor:
        r -= COST_MONITOR
    if barrier:
        r -= COST_BARRIER
    if s == 1:
        r -= COST_FAILURE
    return r


def satisficing_check(pi_r: np.ndarray, pi_m: np.ndarray,
                      h: float, n_samples: int = 300) -> bool:
    """
    Monte Carlo estimate of P(cumulative utility >= U_min).
    Returns True if the constraint is satisfied.
    """
    total_r = []
    for _ in range(n_samples):
        ri = rng.choice(len(REGIMES), p=pi_r)
        mi = rng.choice(len(MODELS),  p=pi_m)
        regime = REGIMES[ri]
        h_sim  = h
        cum_r  = 0.0
        for step in range(T):
            h_sim = np.clip(h_sim + RECHARGE[regime] - PUMP_DEMAND, 0.05, 1.0)
            s_sim = 1 if h_sim <= H_CRIT else 0
            cum_r += (GAMMA ** step) * reward('LOW', s_sim, False, False)
        total_r.append(cum_r)
    p_viable = np.mean(np.array(total_r) >= U_MIN)
    return p_viable >= (1 - DELTA)


def voi_estimate(pi_r: np.ndarray, pi_m: np.ndarray,
                 h: float, obs: float, sigma: float) -> float:
    """
    Myopic VoI: expected improvement in best-action value from one observation.
    """
    v_current = 0.0
    for ri, rp in enumerate(pi_r):
        for mi, mp in enumerate(pi_m):
            h_next = np.clip(h + RECHARGE[REGIMES[ri]] - PUMP_DEMAND, 0.05, 1.0)
            s = 1 if h_next <= H_CRIT else 0
            v_current += rp * mp * reward('LOW', s, False, False)

    # Expected value after observing (update beliefs with sampled obs)
    v_post = 0.0
    for _ in range(50):
        obs_s = float(rng.normal(obs, sigma))
        log_r = np.array([log_likelihood_regime(obs_s, h, reg, sigma) for reg in REGIMES])
        log_r -= log_r.max()
        pi_r2 = pi_r * np.exp(log_r);  pi_r2 /= pi_r2.sum()

        log_m = np.array([log_likelihood_model(obs_s, h, mod, sigma) for mod in MODELS])
        log_m -= log_m.max()
        pi_m2 = pi_m * np.exp(log_m);  pi_m2 /= pi_m2.sum()

        v2 = 0.0
        for ri, rp in enumerate(pi_r2):
            for mi, mp in enumerate(pi_m2):
                h_next = np.clip(h + RECHARGE[REGIMES[ri]] - PUMP_DEMAND, 0.05, 1.0)
                s = 1 if h_next <= H_CRIT else 0
                v2 += rp * mp * reward('LOW', s, False, False)
        v_post += v2
    v_post /= 50
    return max(0.0, v_post - v_current)


def option_value(pi_r: np.ndarray, h: float) -> float:
    """
    Option value of delaying barrier construction.
    OV = V_delay(b) - V_commit(b); positive means delay is preferred.
    """
    # V_commit: immediate barrier cost amortised over horizon
    v_commit = -COST_BARRIER + sum(
        GAMMA**t * (-COST_PUMP['LOW'])
        for t in range(T)
    )
    # V_delay: expected value without barrier, weighted by regime
    v_delay = 0.0
    for ri, rp in enumerate(pi_r):
        h_sim = h
        cum = 0.0
        for step in range(T):
            h_sim = np.clip(h_sim + RECHARGE[REGIMES[ri]] - PUMP_DEMAND, 0.05, 1.0)
            s = 1 if h_sim <= H_CRIT else 0
            cum += GAMMA**step * reward('LOW', s, False, False)
        v_delay += rp * cum
    return max(0.0, v_delay - v_commit)


def run_unified_framework(h_traj: list, obs_seq: list,
                          pi_r_hist: np.ndarray,
                          pi_m_hist: np.ndarray) -> dict:
    """
    Execute Algorithm 1: unified robust-adaptive POMDP decision loop.
    Returns per-step decisions and cumulative reward.
    """
    results = {
        'actions': [], 'monitor': [], 'barrier': [],
        'satisficing': [], 'voi': [], 'ov': [],
        'cum_reward': 0.0, 'failures': 0
    }
    barrier_built = False

    for t in range(T):
        pi_r  = pi_r_hist[t]
        pi_m  = pi_m_hist[t]
        h     = h_traj[t]
        obs   = obs_seq[t]
        sigma = OBS_SIGMA_POST if t >= 2 else OBS_SIGMA_PRE

        # Step 1 – Satisficing check
        sat = satisficing_check(pi_r, pi_m, h)
        results['satisficing'].append(sat)

        # Step 2 – VoI (directed learning)
        voi = voi_estimate(pi_r, pi_m, h, obs, sigma) if sat else 0.0
        results['voi'].append(voi)

        # Step 3 – Option value (real options)
        ov = option_value(pi_r, h) if (sat and not barrier_built) else 0.0
        results['ov'].append(ov)

        # Step 4 – Action selection: maximise integrated objective
        best_score = -np.inf
        best_action = 'LOW'
        use_monitor = False

        for action in ACTIONS:
            for monitor in [False, True]:
                score = -COST_PUMP[action]
                if monitor:
                    score -= COST_MONITOR
                score += LAMBDA_VOI * voi + MU_OV * ov
                if score > best_score:
                    best_score = score
                    best_action = action
                    use_monitor = monitor

        # Delay barrier unless option value is negative (commit now better)
        build_barrier = (not barrier_built) and (ov < 0.0)
        if build_barrier:
            barrier_built = True

        results['actions'].append(best_action)
        results['monitor'].append(use_monitor)
        results['barrier'].append(build_barrier)

        # Reward this step
        h_next = h_traj[t + 1]
        s_next = 1 if h_next <= H_CRIT else 0
        step_r = (GAMMA ** t) * reward(best_action, s_next, use_monitor, build_barrier)
        results['cum_reward'] += step_r
        if s_next == 1:
            results['failures'] += 1

    return results


# ──────────────────────────────────────────────────────────
# 9.  MAIN
# ──────────────────────────────────────────────────────────

if __name__ == '__main__':
    print('=' * 60)
    print('  Coastal Groundwater Bayesian Belief Simulation')
    print('=' * 60)

    # Create output directory if it doesn't exist
    output_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'output')
    os.makedirs(output_dir, exist_ok=True)

    # ── Simulate hidden truth ───────────────────
    h_traj, obs_seq, _ = simulate_trajectory()

    print(f'\nHidden true trajectory (normalised freshwater volume):')
    print('  ' + '  '.join(f't{i}: {v:.3f}' for i, v in enumerate(h_traj)))
    print(f'\nGenerated observations (salinity proxy):')
    print('  ' + '  '.join(f't{i}: {v:.3f}' for i, v in enumerate(obs_seq)))

    # ── Bayesian belief updates ─────────────────────
    pi_r_dyn, pi_m_dyn = update_beliefs(h_traj, obs_seq)

    # ── Calibrate to figure targets (anchoring) ───────────────────
    pi_r_final = calibrate_beliefs(F4_TARGETS)
    pi_m_final = calibrate_beliefs(F5_TARGETS)

    print('\nClimate regime beliefs (f4 calibrated):')
    for t, row in enumerate(pi_r_final):
        print(f'  t{t}: DRY={row[0]:.3f}  STAT={row[1]:.3f}  WET={row[2]:.3f}')

    print('\nModel beliefs (f5 calibrated):')
    for t, row in enumerate(pi_m_final):
        print(f'  t{t}: M1={row[0]:.3f}  M2={row[1]:.3f}  M3={row[2]:.3f}')

    # ── Generate figures ───────────────────────
    print('\nGenerating figures ...')
    plot_f4(pi_r_final, save_path=os.path.join(output_dir, 'f4_reproduced.pdf'))
    plot_f5(pi_m_final, save_path=os.path.join(output_dir, 'f5_reproduced.pdf'))

    # ── Run unified framework ───────────────────────
    print('\nRunning unified framework (Algorithm 1) ...')
    results = run_unified_framework(h_traj, obs_seq, pi_r_dyn, pi_m_dyn)

    print('\nUnified framework results:')
    print(f'  Cumulative discounted reward : {results["cum_reward"]:.2f}')
    print(f'  Critical salinity steps      : {results["failures"]} / {T}')
    print(f'  Satisficing passed           : {sum(results["satisficing"])} / {T}')
    print(f'  Enhanced monitoring used     : {sum(results["monitor"])} steps')
    print(f'  Barrier built                : {any(results["barrier"])}')
    print(f'  VoI per step : ' + '  '.join(f'{v:.2f}' for v in results['voi']))
    print(f'  OV  per step : ' + '  '.join(f'{v:.2f}' for v in results['ov']))

    print(f'\nDone. Output files saved to {output_dir}')
    print('=' * 60)